on:
  push:
    branches: [ master ]

jobs:
  cfcompile:
    runs-on: ubuntu-latest
    container:
      image: adobecoldfusion/coldfusion2023
    env:
      acceptEULA: YES
    steps:
      - uses: actions/checkout@v3

      - name: Compile CFML
        run: /opt/coldfusion/cfusion/bin/cfcompile.sh -cfruntimeuser root -webroot $GITHUB_WORKSPACE -dir $GITHUB_WORKSPACE

  cflint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:latest
    steps:
    - uses: actions/checkout@v3
    - name: Run CFLint
      run: box cflint reportLevel=ERROR

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: cfcompile
    steps:
    - uses: actions/checkout@v3

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }} 
        source: "*,!.gitignore,!.git/*,!.github/*,!.git,!.github"
        target: "ColdFusion/cfusion/wwwroot/bugtracker"

